spring:
  datasource:
    url: jdbc:mysql://localhost:3306/firework_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ajdpwcx
#=======
#    url: jdbc:mysql://localhost:3307/firework_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: qkwdszww211985
#>>>>>>> 5cd355a547469223b773e2e5d6c25f23906527c0
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080 